apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-cass-es.yml -o ./k8s/temporal-cass-es
    kompose.version: 1.26.1 (1b040dd2)
  creationTimestamp: null
  labels:
    io.kompose.service: cassandra
  name: cassandra
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: cassandra
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose-cass-es.yml -o ./k8s/temporal-cass-es
        kompose.version: 1.26.1 (1b040dd2)
      creationTimestamp: null
      labels:
        io.kompose.network/temporal-network: "true"
        io.kompose.service: cassandra
    spec:
      containers:
        - image: cassandra:3.11.9
          name: temporal-cassandra
          ports:
            - containerPort: 9042
          resources: {}
      restartPolicy: Always
status: {}
